### ISSUE TITLE
Waterlines

### ISSUE THREAD

**Issue by gvandendool** [crackernutter/EsriRESTScraper#5]
Do you think your code can be used to scrape data from this service
http://www.pcn.minambiente.it/arcgis/rest/services

Thanks,
Gijs

**Comment by crackernutter** [comment]
It should be able to scrape the individual rest end points of the feature services (those URLs ending in a number). You would need to modify the code to iteratively scape all feature services in a map service and all map services on an ArcGIS server.

Sent using my thumbs

On Mar 16, 2017, at 6:12 AM, gvandendool <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you think your code can be used to scrape data from this service
http://www.pcn.minambiente.it/arcgis/rest/services

Thanks,
Gijs
