### ISSUE TITLE
Problem with GlobalIDs

### ISSUE THREAD

**Issue by SprtnBit** [crackernutter/EsriRESTScraper#8]
I ran into an issue with scraping a rest with a GUID fieldtype while creating a feature class.  I added 

elif 'global' in name.lower():
            fieldType = "GUID"

to the _createField function and it worked.

**Comment by SprtnBit** [comment]
Actually, adding

`'esriFieldTypeGlobalID'
`
to

```
def __setUpdateFields(self, serviceFields):
        """Sets the fields that will be updated from the FeatureService.  This does not include ID or Geometry fields"""
        updateFields = []
        for field in serviceFields:
            if (field['type'] in ['esriFieldTypeOID', 'esriFieldTypeGeometry', 'esriFieldTypeGUID', 'esriFieldTypeGlobalID'] or 'shape' in field['name'].lower() or field['name'] in self.userFields + self.excludeFields):
                pass
            else:
                updateFields.append(field)
        updateFields.insert(
            0, {"name": 'Shape@', "type": "esriFieldTypeGeometry"})
        self.updateFields = updateFields
```

worked far better.

**Comment by crackernutter** [comment]
Thanks for letting me know!  Is the endpoint with GUIDs publicly available, and if so, would you mind sharing it?  I'll run some testing on my end and incorporate your changes.

**Comment by mikepianka** [comment]
I had a similar issue and fixed it by adding 'esriFieldTypeGlobalID' to the list in __setUpdateFields.
